### PR TITLE
Add aarch64 configuration for python, libass, dav1d and ffmpeg

### PR DESCRIPTION
**Pull request by eriktagirov**
Hello, 
First of all thanks for creating this project! It's a pretty ambitious project, and I agree with a lot of the philosophy.
Learned a lot of stuff getting to run on aarch64.
 
I've adjusted/added parameters to be able to compile those 4 packages for the rpi3 and rpi4 (aarch64) to be ​able to watch videos and listen to music with mpv. Everything seems to work apart from strace (WIP)
I thought I could get away with only using predefined macros __aarch64__ and __x86_64__

But when I got to ffmpeg, I had to create 2 new probes to avoid doing extra gymnastics. And be able to fit in one build command. Please let me know if this is a good of way of doing it. 

If it is, I will configure strace package using a similar technique (The last package I need to compile) but it's trickier because I run an older version of the kernel so I need to compile it with the correct headers... 

BR

### CODE REVIEW

**Comment by michaelforney** [comment]
Apologies, looks like I started a review but forgot to hit send. I'm still interested in merging these changes, but I think you should split them into one commit per package.

**Comment by eriktagirov** [comment]
Hey, no worries you seem like a busy individual :)
Thanks for the feedback, I will fix the indentation, and remove the unnecessary definitions.
And will resubmit a proper PR with the strace package working on ARM64

I want to thank you for making this distribution!
Looking back, during the installation I skipped 'the part' that sets the permissions on the root dir.
so getting perp to run was a hassle because I had to set the correct permissions by hand.
And to figure that out, I had to go peak at the musl glibc source code, to see why,
It helped (a lot) to understand the intricacies of a *NIX system. 
Because the source code to everything is approachable,
I could figure out what went wrong. And since then it pushed me to read some good literature. 
It's a perfect starting to point to get involved in the development of libre software. 
IMHO, there is no better development environment than the *NIX environment..

Most importantly, on a personal note, it really helped me lot to not regret my career choice that I made long ago. 
After 3 years of building bloat, on evil platforms and using 'bloated web frameworks' that are designed to gimp and hurt developers.. Obeying to absolute 'UX noobs', collaborating with other 'web devs'... Just jaded me so much!  
it nearly made quit and become a gardener or something.. Took a break, then came across this distribution!

**Comment by kt0f** [comment]
Hi, I fixed the indentation and separated the commits: https://github.com/kt0f/oasis/commits/3886c884eebf83e46ca7bc2fdab61c545d4085b8

Would this be mergeable?

**Comment by TheMBL09898** [comment]
Any development on this? I'm interested in building oasis on an rpi.

**Pull request closed without merging**
